### ISSUE TITLE
知乎过来的。有点迷

### ISSUE THREAD

**Issue by SimonZhangITer** [csvwolf/Sky_WeiboServices#3]
坚持写博客、作总结
我也这么做过两年 后来越写越少 博客网站也换了好几个....

看到你之后貌似又有了些动力
先粉上
作为精神支柱
:thumbsup::thumbsup::thumbsup:

**Comment by csvwolf** [comment]
谢谢 但是 issue 是用于提项目相关的，如果希望交流可以前往博客留言，这个先关了
